name: ci

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci.yml"


jobs:

  matlab:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: R2022b

    - name: Run tests
      uses: matlab-actions/run-build@v1
