name: ci

on:
  push:
    paths:
      - "**.m"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-suggests --no-install-recommends octave > /dev/null
    - run: octave --eval "matmap3d.tests.test_unit; exit"
