name: ci

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci.yml"


jobs:

  matlab:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        release: [R2020a, R2023b]

    steps:
    - uses: actions/checkout@v4

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.release }}

    - name: Run Matlab tests (buildtool)
      if: ${{ matrix.release >= 'R2022b' }}
      timeout-minutes: 10
      uses: matlab-actions/run-build@v1

    - name: Run tests (manual)
      if: ${{ matrix.release < 'R2022b' }}
      timeout-minutes: 10
      uses: matlab-actions/run-tests@v1
      with:
        strict: true
