name: ci

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci.yml"


jobs:

  matlab:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        release: [R2020a, R2020b, R2021b, R2022b]

    steps:
    - uses: actions/checkout@v3

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.release }}

    - name: Run Matlab tests (buildtool)
      if: ${{ matrix.release == 'R2022b' }}
      timeout-minutes: 15
      uses: matlab-actions/run-build@v1

    - name: Run tests (manual)
      if: ${{ matrix.release != 'R2022b' }}
      timeout-minutes: 15
      uses: matlab-actions/run-command@v1
      with:
        command: |
          r = runtests('matmap3d');
          assert(~isempty(r), "No tests were run")
          assertSuccess(r)
